server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: API-GATEWAY

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      hibernate.SQL: DEBUG
      springframework.web: DEBUG
      springframework.data: DEBUG
      boot.autoconfigure.data.rest: DEBUG
      boot.autoconfigure.data.jpa: DEBUG
      boot.autoconfigure.orm: DEBUG
