CREATE TABLE address (
  address_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  full_address VARCHAR(255),
  postal_code VARCHAR(255),
  city VARCHAR(255),
  user_id INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);